### ISSUE TITLE
Redo audio formats for songs

### ISSUE THREAD

**Issue by PikaDude** [PikaDude/Animal-Crossing-Music-Extension#1]
Some songs, such as the ACNL music is stored at a crazy 499kbps, despite the fact that the original soundtrack from the games files only exists at 299kbps. This is substantially larger than required and is also insane for any audio format. Songs need to be reduced to 320kbps maximum to reduce file size. Some songs for other games are also of lower quality than what's available and also contain audible artefacts of their lower quality.

## Progress

- [x] **Animal Crossing (Sunny)**:
- ✔71.0mb (320kb/s)
- ✔audible quality is good
- [x] **Animal Crossing (Snowing)**:
- ✔68.9mb (320kb/s)
- ✔audible quality is good
- [x] **Animal Crossing (Cheery)**:
- ✔68.0mb (320kb/s)
- ✔audible quality is good
- [ ] **Animal Crossing (Events)**
- [x] **City Folk/Wild World (Sunny)**:
- ✔56.2mb (208kb/s)
- ✔some songs have soft static and some have audible buzzing, there don't appear to be any high quality rips without these issues. doesn't appear to be incredibly noticeable unless you have the song at a deafening volume, and it's only a handful of songs, so i think it should be fine
- [x] **City Folk/Wild World (Snowing)**:
- ✔59.0mb (208kb/s)
- ✔some songs have soft static and some have audible buzzing, there don't appear to be any high quality rips without these issues. doesn't appear to be incredibly noticeable unless you have the song at a deafening volume, and it's only a handful of songs, so i think it should be fine
- [x] **City Folk/Wild World (Raining)**:
- ✔55.4mb (208kb/s)
- ✔some songs have soft static and some have audible buzzing, there don't appear to be any high quality rips without these issues. doesn't appear to be incredibly noticeable unless you have the song at a deafening volume, and it's only a handful of songs, so i think it should be fine
- [ ] **City Folk/Wild World (Events)**
- [x] **New Leaf (Sunny)**:
- ✔71.4mb (300kb/s)
- ✔audible quality is good
- [x] **New Leaf (Raining)**:
- ✔62.9mb (300kb/s)
- ✔audible quality is good
- [x] **New Leaf (Snowing)**: 
- ✔70.1mb (300kb/s)
- ✔audible quality is now good
- [ ] **New Leaf (Events)**
- [x] **KK (Live)**
- ✔291mb (192/320/kb/s) (CF/WW songs are 192kb/s as a higher version isn't available)
- ✔audible quality is good
- ✔contains all kk songs from ac and ww/cf (81 songs, hence the large size)
- [x] **KK (Aircheck)**
- ✔173mb (208/320kb/s) (CW/WW songs are 208kb/s as a higher version isn't available)
- ✔audible quality is good
- ✔contains all kk songs from ac and ww/cf (75 songs, hence the large size)

**Comment by jordigarcl** [comment]
Giving public visibility to [the issue](https://github.com/animal-crossing-music-extension/Animal-Crossing-Music-Extension/issues/9) from the original project.

**Comment by PikaDude** [comment]
Opus actually makes the file sizes larger. The reason why they were much smaller is because no bitrate was specified, and ffmpeg decreased the bitrate to most likely 128kb/s. The ACNL soundtrack is stored at 499kb/s which is insane, and I'm pretty sure that the original soundtrack was only 299kb/s meaning that the bitrate was unnecessarily increased too. So I'm in the process of reducing them to 160kb/s vorbis files. You honestly won't be able to tell the difference.

**Comment by PikaDude** [comment]
**Progress:**

- [ ] **Animal Crossing**
- [ ] **City Folk**
- [ ] **City Folk (Snowing)**
- [x] **New Leaf**: 55.8mb -> 22.8mb
- [x] **New Leaf (Raining)**: 66.7mb -> 24.5mb
- [ ] **New Leaf (Snowing)**: Low quality game-rips with static. Looking for better quality rips.

**Comment by PikaDude** [comment]
Issue moved to animal-crossing-music-extension/ac-music-extension#54
