### ISSUE TITLE
Clean code

### ISSUE THREAD

**Issue by PikaDude** [PikaDude/Animal-Crossing-Music-Extension#10]
A lot of things are written quite poorly, featuring redundant, messy and obsolete code. The code needs to be gone through and cleaned.

**Comment by jordigarcl** [comment]
Should we agree on a code style guide?
Should we refactor the code to use ES6 classes?

Also, maybe we should take into account the upcoming Chrome Manifest V3 which will deprecate the `background.scripts` field that will be replaced by `background.service_worker`

If we are to refactor the code we could do so having the next specification in mind!

**Comment by paladique** [comment]
Agreed. +1 to all of this.

Since a release hasn't been out in a while, it would be nice to get it to a stable point and fix all the severe issues, do a release, then focus on refactoring. Thoughts?

**Comment by PikaDude** [comment]
That's the goal, yeah. Refactoring isn't really a big issue - if it works, it works.

**Comment by PikaDude** [comment]
Issue discussion moved to animal-crossing-music-extension/ac-music-extension#51
