### ISSUE TITLE
Play nice with Chrome 79's new Media Playback Controls

### ISSUE THREAD

**Issue by jordigarcl** [PikaDude/Animal-Crossing-Music-Extension#11]
Chrome 79 brought a new [Media Playback Control feature](https://beebom.com/chrome-79-media-playback-controls-address-bar/) that is still rolling out to some users. It appeared on my browser yesterday.

This is how it looks:
<img width="476" alt="Screenshot 2020-01-12 at 12 59 20" src="https://user-images.githubusercontent.com/16718039/72218511-b8eb6a80-353b-11ea-98ab-2ef432d37be0.png">

It is basically a button in the sidebar that shows up when something in the browser is playing music. 

I guess its intended use is to better control music playing on other tabs e.g youtube. But, as you can see above, it will also trigger whenever the extension plays music. And the result is not nice.

We could investigate this new feature (did some quick research and did not found any official documentation) and either disable it for our extension (if that's even possible) or leverage it and try to use the artist, title and album art fields to our advantage. 

We might even enable 'back' and 'next' buttons when listening to KK!

**Comment by PikaDude** [comment]
Actually quite an old feature that integrated with Windows 10's keyboard media controls and volume control area for quite some time. It only recently was implemented into the desktop's browser UI itself. Here's the relevant documentation: https://developers.google.com/web/updates/2017/02/media-session

**Comment by jordigarcl** [comment]
Cool! I see the example boilerplate code they provide works perfectly out of the box. 
It looks like integrating it with the code would not be much of a trouble.

I guess for the time being with only want to support play/pause in the same way we do when we start and stop the extension. 

We can use something like:
* Title: `7pm (Sunny)`
* Artist: `Animal Crossing - New Leaf`
* Album: `Animal Crossing Music Extension`

<img width="404" alt="Screenshot 2020-01-13 at 22 22 58" src="https://user-images.githubusercontent.com/16718039/72293239-63a27c80-3653-11ea-814c-86ae4320dbbe.png">

I don't know if there is a way to get rid of the `chrome-extension://xxxxx` header, since it looks it extracts it from the title.

-----

For future reference, the MediaSession API Documentation can be found [here](https://github.com/w3c/mediasession). Note that Chrome's implementation may differ (e.g. the examples show that `metadata.artwork.src` can be a path to a local file but Chrome complains that it must be a `http/https/data/blob schema).

**Comment by PikaDude** [comment]
Perhaps try setting the background page title using JS?

**Comment by jordigarcl** [comment]
Tried that before discovering about the MediaSession documentation and it seemed to affect the 'song title'. Will check tomorrow!

**Edit:**
Yeah, it looks like `document.title`is just the fallback value when `metadata.artist` is not defined.

**Edit 2:** Changing the extension page url with `	window.history.pushState()` didn't help either.

**Comment by PikaDude** [comment]
By the way, how is the album art working? Do we need to include assets for them or is it able to grab the album art from the song files metadata?

**Comment by jordigarcl** [comment]
Not 100% sure about embedded album art until I try but I did write artist and album title metadata to a ogg file and they were ignored.

I ended up searching for HD game covers, cropping them to 512x512 and uploading them to imgur. There should be a way to use local files though!

**Comment by PikaDude** [comment]
It's safe to assume that it ignores album art I guess. If you have it all working, you can push it to a feature branch and I'll get it working with local files if you want.

**Comment by jordigarcl** [comment]
I just pasted the boilerplate code into `main.js` and tweaked around the metadata values to see what it looked like.

I will create a feature branch for this and see the cleanest way to implement it in the code. It should be trivial to create a pair of dictionaries to properly format `title` and `album`.

**Comment by jordigarcl** [comment]
I did some work on this (see draft PR). I am missing a definition for KK live/aircheck. 
How do you think it should look like?
