### ISSUE TITLE
README is out of date and needs a revamp

### ISSUE THREAD

**Issue by PikaDude** [PikaDude/Animal-Crossing-Music-Extension#2]

**Comment by jordigarcl** [comment]
It would be nice to clean it up a little bit and separate the features checklist into a separate markdown file, the wiki, or a Github Project.

Additionally, we could set up [Contribution Guidelines](https://opensource.guide/starting-a-project/) (there are [many](https://mozillascience.github.io/working-open-workshop/contributing/) templates around the web) so contributors can collaborate more efficiently!

**Comment by jordigarcl** [comment]
I'm going to work on how we can update and improve the current README

**Comment by jordigarcl** [comment]
I think we can close this issue and (eventually) open a new one to include Contribution guidelines

**Comment by PikaDude** [comment]
Yup, sounds good.
