### ISSUE TITLE
Consider creating a Github Page for the project

### ISSUE THREAD

**Issue by jordigarcl** [PikaDude/Animal-Crossing-Music-Extension#3]
We could consider creating a simple static website for the project using the 'Github Pages' feature.
This could serve as a "product presentation page" to promote the extension, and it would be aimed to end-users.

Its initial structure could be as simple as a single landing page explaining what the extension is about, the features it provides, and links to the Chrome Extension Page, Repository, etc.

This is in no way a priority, just a nice thing to have that wouldn't take that much effort!

**Comment by paladique** [comment]
Love this idea! I think once we merge into the other repo this would be great. 

Another idea to go with this 💡: set up a way for users who don't have a github acct to report problems/bugs there too. A bot initially comes to mind.

**Comment by jordigarcl** [comment]
I'm gonna create a Github Page on my fork repo to see what can we came up with 👍

**Comment by jordigarcl** [comment]
Just wanted to give visibility that I'm toying with a [very rough jekyll gh page](https://jordigarcl.github.io/ac-music-extension-revived/). Focusing on the content at the moment.

**Comment by PikaDude** [comment]
Looks good so far! Did we decide to keep the revived prefix or not?

**Comment by jordigarcl** [comment]
It is my understanding that we will be ditching it. We should probably start removing the prefix from all places 👍

**Comment by jordigarcl** [comment]
Did more work there. Would love some feedback. There are many things I don't like UI-wise but I'm no designer (or frontender for that matter).

Striving for a minimum viable product here so we (or more talented people) can later improve it!

Putting the link again for visibility
https://jordigarcl.github.io/ac-music-extension-revived/

**Comment by jordigarcl** [comment]
Closing the issue as the page has already been created. Further discussion should occur on the page repo: https://github.com/animal-crossing-music-extension/animal-crossing-music-extension.github.io
