### ISSUE TITLE
Consider master protections

### ISSUE THREAD

**Issue by jordigarcl** [PikaDude/Animal-Crossing-Music-Extension#4]
I see 05c8ff1 and f8c3241  brought `master` back to a stable state.

I think the reason for `master` crashing was the result of merging perfectly fine PRs without ensuring sure they were properly integrated. For that reason I believe we should consider setting up some protections around it so ensure its stability:

1. Adopt a branching model to introduce changes more safely. I personally think a simplified [git flow](https://nvie.com/posts/a-successful-git-branching-model/) would suit the project needs.  That is, using `master` for published versions, `develop` for integrating finished features and `feat-xxx`/`fix-xxx` branches to work on features and bug fixes.
2. Make `develop` the default branch (so new PRs are made against it) and aim to keep it stable
3. Require approved PRs to merge commits to `master` and `develop` (this does not apply to admins)

**Comment by PikaDude** [comment]
I don't believe feat-xxx and fix-xxx branches would be needed, I think we should just stick with master and dev branches, it's what a lot of people tend to do these days. Master would be the one that's always stable while dev would be used for things still in development and perhaps not as stable. Having the feat/fix branches tends to cause lots of clutter and confusion and just ends up making things a bit messier when it comes to assembling branches together. Also if we are to make dev the default branch, we should definitely indicate in the README that it may not be as stable as the master branch.

**Comment by jordigarcl** [comment]
My reasoning for `develop`  being the default was so `master` could always reflect the latest released version, in case we don't want to publish a new release every time we integrate code. 

If I understood you correctly, we can do that by having master be the stable branch and making develop the one to merge all PRs to. For that, I think it is better to make develop 'the default' so Github automatically assigns all new PRs to it and new contributors don't get confused.

Of course, this comes with the drawback of having to indicate this in the documentation, as being the default also means that this will be the branch shown in the homepage of the repository.

This is a Github inconvenience! It should allow users to differentiate between the 'stable' branch and the default to merge PRs against =/

Do you have a different proposal?

**Comment by PikaDude** [comment]
Actually, I thought about it a bit more, and I think we'll go with your original proposal for the simplified git flow model.
