### ISSUE TITLE
Clean up the repository

### ISSUE THREAD

**Issue by jordigarcl** [PikaDude/Animal-Crossing-Music-Extension#6]
This is more of a personal opinion, but I feel the repo would look better if:

- [X] We changed the name to something plainer in lowercase, like `ac-music-chrome-extension`
- [ ] We added a `chrome-extension` tag
- [X] We improved documentation (see #2)
- [x] We removed support for unused Github features (Actions, Projects, Wiki)
- [x] We removed all stale branches
- [ ] We used the `url` repo attribute to point to the Original Extension page
- [ ] We moved the feature checklist from the previous README into a wiki page

**Comment by PikaDude** [comment]
We could probably use projects for todos and stuff actually. It's a bit like Trello from what I've heard.

**Comment by jordigarcl** [comment]
Good idea! Never tried it before but I guess we could make use of it.
I will see what I can do with it in my fork 👍

**Comment by jordigarcl** [comment]
I have messed for a few minutes with it and it definitely looks like a Trello with fewer features but fully-integrated with repository issues and PRs. 

It allows you to create a board, create columns within the board and either move cards from one column to another or archive them. There is a card for every created issue and you can also create your own cards. An usage example can be found in the [Bootstrap repository](https://github.com/twbs/bootstrap/projects).

I believe it can be useful in the future but right now might be a bit overkill, since we can already keep track of all features and TODOs in issues.

**Comment by PikaDude** [comment]
Fair enough, I'll go ahead and disable projects.

**Comment by jordigarcl** [comment]
Closing this as I feel the repo is in a much better state already
